local ParameterList = require('cmantic.parameter_list')
local eq = assert.are.same

describe('parameter_list', function()
  describe('new', function()
    it('should create empty param list from nil', function()
      local pl = ParameterList.new(nil)
      eq({}, pl.params)
      eq(0, pl:count())
    end)

    it('should create empty param list from empty string', function()
      local pl = ParameterList.new('')
      eq({}, pl.params)
      eq(0, pl:count())
    end)

    it('should create single-parameter list from "int x"', function()
      local pl = ParameterList.new('int x')
      eq(1, pl:count())
      eq('int', pl.params[1].type)
      eq('x', pl.params[1].name)
    end)

    it('should create multi-parameter list from "int x, float y, char z"', function()
      local pl = ParameterList.new('int x, float y, char z')
      eq(3, pl:count())
      eq('int', pl.params[1].type)
      eq('x', pl.params[1].name)
      eq('float', pl.params[2].type)
      eq('y', pl.params[2].name)
      eq('char', pl.params[3].type)
      eq('z', pl.params[3].name)
    end)

    it('should set raw field to original text', function()
      local text = 'int x, float y'
      local pl = ParameterList.new(text)
      eq(text, pl.raw)
    end)

    it('should set raw field to empty string for nil input', function()
      local pl = ParameterList.new(nil)
      eq('', pl.raw)
    end)
  end)

  describe('_parse', function()
    it('should return empty table for nil', function()
      eq({}, ParameterList._parse(nil))
    end)

    it('should return empty table for empty string', function()
      eq({}, ParameterList._parse(''))
    end)

    it('should split on commas correctly', function()
      local params = ParameterList._parse('int a, float b')
      eq(2, #params)
      eq('a', params[1].name)
      eq('b', params[2].name)
    end)

    it('should NOT split on commas inside template brackets', function()
      local params = ParameterList._parse('std::map<int, float> m, int n')
      eq(2, #params)
      eq('m', params[1].name)
      eq('n', params[2].name)
      eq('std::map<int, float>', params[1].type)
    end)

    it('should NOT split on commas inside parentheses', function()
      local params = ParameterList._parse('void (*fp)(int, float), int n')
      eq(2, #params)
      eq('n', params[2].name)
      eq('int', params[2].type)
    end)

    it('should NOT split on commas inside braces', function()
      local params = ParameterList._parse('std::function<void()> f, int n')
      eq(2, #params)
      eq('f', params[1].name)
      eq('n', params[2].name)
    end)

    it('should trim whitespace around parameters', function()
      local params = ParameterList._parse('  int x  ,  float y  ')
      eq(2, #params)
      eq('int', params[1].type)
      eq('x', params[1].name)
      eq('float', params[2].type)
      eq('y', params[2].name)
    end)

    it('should handle whitespace-heavy input', function()
      local params = ParameterList._parse('  int   x  ,  float  y  ')
      eq(2, #params)
      eq('x', params[1].name)
      eq('y', params[2].name)
      eq('int', params[1].type)
      eq('float', params[2].type)
    end)

    it('should handle single parameter with no commas', function()
      local params = ParameterList._parse('int x')
      eq(1, #params)
      eq('x', params[1].name)
    end)

    it('should handle trailing comma gracefully', function()
      local params = ParameterList._parse('int x,')
      eq(1, #params)
      eq('x', params[1].name)
    end)

    it('should handle leading comma gracefully', function()
      local params = ParameterList._parse(', int x')
      eq(1, #params)
      eq('x', params[1].name)
    end)

    it('should handle nested template brackets', function()
      local params = ParameterList._parse('std::map<std::vector<int>, float> m, int n')
      eq(2, #params)
      eq('m', params[1].name)
      eq('n', params[2].name)
    end)
  end)

  describe('_parse_param', function()
    it('should parse simple "int x"', function()
      local p = ParameterList._parse_param('int x')
      eq('int x', p.full_text)
      eq('int', p.type)
      eq('x', p.name)
    end)

    it('should parse parameter with default value', function()
      local p = ParameterList._parse_param('int x = 5')
      eq('int x = 5', p.full_text)
      eq('int', p.type)
      eq('x', p.name)
    end)

    it('should parse const reference', function()
      local p = ParameterList._parse_param('const std::string& ref')
      eq('const std::string& ref', p.full_text)
      eq('const std::string&', p.type)
      eq('ref', p.name)
    end)

    it('should parse pointer attached to type', function()
      local p = ParameterList._parse_param('int* ptr')
      eq('int*', p.type)
      eq('ptr', p.name)
    end)

    it('should parse pointer attached to name', function()
      local p = ParameterList._parse_param('int *ptr')
      eq('int *', p.type)
      eq('ptr', p.name)
    end)

    it('should parse reference', function()
      local p = ParameterList._parse_param('int& ref')
      eq('int&', p.type)
      eq('ref', p.name)
    end)

    it('should parse template type', function()
      local p = ParameterList._parse_param('std::vector<int> items')
      eq('std::vector<int>', p.type)
      eq('items', p.name)
    end)

    it('should parse array type as type-only (name empty)', function()
      local p = ParameterList._parse_param('int arr[10]')
      -- Square brackets are not masked, so the trailing ] prevents name extraction
      -- The entire text becomes the type, name is empty
      eq('int arr[10]', p.type)
      eq('', p.name)
    end)

    it('should handle parameter with only type (no name)', function()
      local p = ParameterList._parse_param('int')
      -- Single word: the code sets name to the word and type to empty
      eq('int', p.name)
      eq('', p.type)
    end)

    it('should handle complex type with default using braces', function()
      local p = ParameterList._parse_param('T val = T{}')
      eq('T val = T{}', p.full_text)
      eq('T', p.type)
      eq('val', p.name)
    end)

    it('should parse double pointer', function()
      local p = ParameterList._parse_param('int** ptr')
      eq('int**', p.type)
      eq('ptr', p.name)
    end)

    it('should parse const pointer', function()
      local p = ParameterList._parse_param('const int* ptr')
      eq('const int*', p.type)
      eq('ptr', p.name)
    end)

    it('should parse pointer to const', function()
      local p = ParameterList._parse_param('int const* ptr')
      eq('int const*', p.type)
      eq('ptr', p.name)
    end)

    it('should parse default value with string literal', function()
      local p = ParameterList._parse_param('std::string name = "default"')
      eq('std::string', p.type)
      eq('name', p.name)
    end)

    it('should parse default value with nested angle brackets', function()
      local p = ParameterList._parse_param('std::vector<int> v = std::vector<int>()')
      eq('std::vector<int>', p.type)
      eq('v', p.name)
    end)

    it('should parse template type with multiple params', function()
      local p = ParameterList._parse_param('std::map<int, std::string> items')
      eq('std::map<int, std::string>', p.type)
      eq('items', p.name)
    end)

    it('should parse rvalue reference', function()
      local p = ParameterList._parse_param('std::string&& val')
      eq('std::string&&', p.type)
      eq('val', p.name)
    end)

    it('should preserve full_text with default value', function()
      local p = ParameterList._parse_param('float ratio = 0.5f')
      eq('float ratio = 0.5f', p.full_text)
      eq('float', p.type)
      eq('ratio', p.name)
    end)

    it('should handle parameter with underscore in name', function()
      local p = ParameterList._parse_param('int my_var')
      eq('int', p.type)
      eq('my_var', p.name)
    end)

    it('should handle unsigned type', function()
      local p = ParameterList._parse_param('unsigned int count')
      eq('unsigned int', p.type)
      eq('count', p.name)
    end)
  end)

  describe('count', function()
    it('should return 0 for empty parameter list', function()
      local pl = ParameterList.new('')
      eq(0, pl:count())
    end)

    it('should return 1 for single parameter', function()
      local pl = ParameterList.new('int x')
      eq(1, pl:count())
    end)

    it('should return N for N parameters', function()
      local pl = ParameterList.new('int a, float b, char c, double d')
      eq(4, pl:count())
    end)

    it('should return 0 for nil input', function()
      local pl = ParameterList.new(nil)
      eq(0, pl:count())
    end)
  end)

  describe('names', function()
    it('should return empty table for no parameters', function()
      local pl = ParameterList.new('')
      eq({}, pl:names())
    end)

    it('should return {"x"} for single parameter', function()
      local pl = ParameterList.new('int x')
      eq({ 'x' }, pl:names())
    end)

    it('should return all names for multiple parameters', function()
      local pl = ParameterList.new('int x, float y, char z')
      eq({ 'x', 'y', 'z' }, pl:names())
    end)

    it('should return name for type-only parameter as the type word', function()
      -- For "int" with no name, name field gets the word "int"
      local pl = ParameterList.new('int')
      eq({ 'int' }, pl:names())
    end)

    it('should return empty string for array-type parameter', function()
      local pl = ParameterList.new('int arr[10]')
      eq({ '' }, pl:names())
    end)
  end)

  describe('types', function()
    it('should return empty table for no parameters', function()
      local pl = ParameterList.new('')
      eq({}, pl:types())
    end)

    it('should return single type for one parameter', function()
      local pl = ParameterList.new('int x')
      eq({ 'int' }, pl:types())
    end)

    it('should return full type including const and reference modifiers', function()
      local pl = ParameterList.new('int x, const std::string& ref')
      eq({ 'int', 'const std::string&' }, pl:types())
    end)

    it('should preserve pointer in type', function()
      local pl = ParameterList.new('int* ptr, float& ref')
      eq({ 'int*', 'float&' }, pl:types())
    end)

    it('should preserve template types', function()
      local pl = ParameterList.new('std::vector<int> items, std::map<int, float> m')
      eq({ 'std::vector<int>', 'std::map<int, float>' }, pl:types())
    end)

    it('should return empty string type for type-only parameter', function()
      -- For "int" with no name, type field is empty
      local pl = ParameterList.new('int')
      eq({ '' }, pl:types())
    end)

    it('should return full array type for array parameter', function()
      local pl = ParameterList.new('int arr[10]')
      eq({ 'int arr[10]' }, pl:types())
    end)
  end)
end)
