local parse = require('cmantic.parsing')
local eq = assert.are.same

describe('parsing', function()
  describe('is_blank', function()
    it('returns true for nil', function()
      assert.is_true(parse.is_blank(nil))
    end)
    it('returns true for empty string', function()
      assert.is_true(parse.is_blank(''))
    end)
    it('returns true for whitespace only', function()
      assert.is_true(parse.is_blank('   \t\n  '))
    end)
    it('returns false for non-empty text', function()
      assert.is_false(parse.is_blank('hello'))
    end)
  end)

  describe('trim', function()
    it('trims leading and trailing whitespace', function()
      eq('hello', parse.trim('  hello  '))
    end)
    it('returns empty for nil', function()
      eq('', parse.trim(nil))
    end)
    it('returns empty for whitespace only', function()
      eq('', parse.trim('   \t\n  '))
    end)
  end)

  describe('normalize_whitespace', function()
    it('collapses multiple spaces to single', function()
      eq('a b c', parse.normalize_whitespace('a   b   c'))
    end)
    it('trims edges', function()
      eq('hello world', parse.normalize_whitespace('  hello world  '))
    end)
    it('returns empty for nil', function()
      eq('', parse.normalize_whitespace(nil))
    end)
  end)

  describe('mask_comments', function()
    it('masks single-line comments', function()
      local input = 'int x; // comment'
      local masked = parse.mask_comments(input)
      assert.is_not_nil(masked:find('int x;'))
      eq(true, masked:sub(#input - #' comment' + 1):match('^%s+$') ~= nil)
    end)
    it('masks block comments', function()
      local input = 'int x; /* block */ int y;'
      local masked = parse.mask_comments(input)
      assert.is_not_nil(masked:find('int x;'))
      assert.is_not_nil(masked:find('int y;'))
      local _, _, between = masked:find('int x;( *)int y;')
      assert.is_not_nil(between)
    end)
    it('masks multiline block comments', function()
      local input = 'int x; /* line1\nline2 */ int y;'
      local masked = parse.mask_comments(input)
      assert.is_not_nil(masked:find('int x;'))
      assert.is_not_nil(masked:find('int y;'))
    end)
    it('preserves code outside comments', function()
      eq('int x; ', parse.mask_comments('int x; '))
    end)
    it('returns empty for nil', function()
      eq('', parse.mask_comments(nil))
    end)
    it('handles unclosed block comment (EOF before */)', function()
      local input = 'int x; /* unclosed comment'
      local masked = parse.mask_comments(input)
      assert.is_not_nil(masked:find('int x;'))
      -- Everything after /* should be spaces
      local tail = masked:sub(#'int x; ' + 1)
      eq(true, tail:match('^%s*$') ~= nil)
    end)
    it('handles multiple consecutive single-line comments', function()
      local input = 'int x;\n// line1\n// line2\n// line3\nint y;'
      local masked = parse.mask_comments(input)
      assert.is_not_nil(masked:find('int x;'))
      assert.is_not_nil(masked:find('int y;'))
      assert.is_nil(masked:find('line1'))
      assert.is_nil(masked:find('line3'))
    end)
  end)

  describe('mask_quotes', function()
    it('masks double-quoted strings', function()
      local input = 'printf("hello world");'
      local masked = parse.mask_quotes(input)
      assert.is_not_nil(masked:find('printf'))
      assert.is_not_nil(masked:find(');'))
      local _, s = masked:find('printf%(')
      local e, _ = masked:find('%);')
      local middle = masked:sub(s + 1, e - 1)
      eq(true, middle:match('^%s+$') ~= nil)
    end)
    it('masks single-quoted chars', function()
      local input = "char c = 'a';"
      local masked = parse.mask_quotes(input)
      assert.is_not_nil(masked:find('char c ='))
      assert.is_not_nil(masked:find(';'))
    end)
    it('handles escaped quotes', function()
      local input = 'printf("say \\"hi\\"");'
      local masked = parse.mask_quotes(input)
      assert.is_not_nil(masked:find('printf'))
      assert.is_not_nil(masked:find(');'))
    end)
    it('returns empty for nil', function()
      eq('', parse.mask_quotes(nil))
    end)
    it('handles empty string literal', function()
      local input = 'const char* s = "";'
      local masked = parse.mask_quotes(input)
      assert.is_not_nil(masked:find('const char%* s ='))
      assert.is_not_nil(masked:find(';'))
      local _, assign_end = masked:find('const char%* s = ')
      local rest = masked:sub(assign_end + 1)
      local before_semi = rest:match('^(%s*)%;')
      assert.is_not_nil(before_semi)
    end)
    it('handles unclosed double quote (no closing ")', function()
      local input = 'char* s = "unclosed;'
      local masked = parse.mask_quotes(input)
      assert.is_not_nil(masked:find('char%* s ='))
      local tail = masked:sub(#'char* s = ' + 1)
      eq(true, tail:match('^%s*$') ~= nil)
    end)
    it('handles unclosed single quote', function()
      local input = "char c = 'a"
      local masked = parse.mask_quotes(input)
      assert.is_not_nil(masked:find('char c ='))
      local tail = masked:sub(#'char c = ' + 1)
      eq(true, tail:match('^%s*$') ~= nil)
    end)
  end)

  describe('mask_raw_strings', function()
    it('masks R"delim(...)delim" literals', function()
      local input = 'auto s = R"raw(hello world)raw";'
      local masked = parse.mask_raw_strings(input)
      assert.is_not_nil(masked:find('auto s ='))
      assert.is_not_nil(masked:find(';'))
    end)
    it('returns empty for nil', function()
      eq('', parse.mask_raw_strings(nil))
    end)
  end)

  describe('mask_attributes', function()
    it('masks [[nodiscard]]', function()
      local input = '[[nodiscard]] int foo();'
      local masked = parse.mask_attributes(input)
      assert.is_not_nil(masked:find('int foo'))
    end)
    it('masks [[deprecated("msg")]]', function()
      local input = '[[deprecated("use bar")]] void foo();'
      local masked = parse.mask_attributes(input)
      assert.is_not_nil(masked:find('void foo'))
    end)
  end)

  describe('mask_non_source_text', function()
    it('chains all masks in order', function()
      local input = 'int x = 42; // comment\nstd::string s = "hello"; /* block */'
      local masked = parse.mask_non_source_text(input)
      assert.is_not_nil(masked:find('int x = 42;'))
      assert.is_nil(masked:find('comment'))
      assert.is_nil(masked:find('hello'))
      assert.is_nil(masked:find('block'))
    end)
    it('preserves character positions', function()
      local input = 'void foo(); // comment'
      local masked = parse.mask_non_source_text(input)
      eq('void foo();', masked:sub(1, 11))
    end)
  end)

  describe('mask_balanced', function()
    it('masks parentheses content', function()
      local input = 'foo(bar, baz)'
      local masked = parse.mask_balanced(input, '(', ')', false)
      assert.is_not_nil(masked:find('foo'))
      local inner = masked:match('foo(%s*)')
      assert.is_not_nil(inner)
    end)
    it('keeps enclosing delimiters when keep_enclosing=true', function()
      local input = 'foo(bar)'
      local masked = parse.mask_balanced(input, '(', ')', true)
      assert.is_not_nil(masked:find('%('))
      assert.is_not_nil(masked:find('%)'))
    end)
    it('masks angle brackets with operator disambiguation', function()
      local input = 'vector<int> x;'
      local masked = parse.mask_angle_brackets(input, false)
      assert.is_not_nil(masked:find('vector'))
      assert.is_not_nil(masked:find('x'))
      assert.is_nil(masked:find('int'))
    end)
    it('does not confuse <= with angle bracket', function()
      local input = 'if (a <= b)'
      local masked = parse.mask_angle_brackets(input, false)
      assert.is_not_nil(masked:find('<='))
    end)
    it('handles nested balanced brackets', function()
      local input = 'foo((a, b), c)'
      local masked = parse.mask_balanced(input, '(', ')', false)
      assert.is_not_nil(masked:find('foo'))
      assert.is_nil(masked:find('a'))
      assert.is_nil(masked:find('b'))
      assert.is_nil(masked:find('c'))
    end)
    it('handles unmatched left delimiter', function()
      local input = 'foo(bar'
      local masked = parse.mask_balanced(input, '(', ')', false)
      assert.is_not_nil(masked:find('foo'))
      eq('(', input:sub(4, 4))
    end)
    it('disambiguates >> as operator (not two angle bracket closes)', function()
      local input = 'int x = a >> 2;'
      local masked = parse.mask_angle_brackets(input, false)
      assert.is_not_nil(masked:find('>>'))
    end)
    it('disambiguates >= as operator', function()
      local input = 'if (a >= b)'
      local masked = parse.mask_angle_brackets(input, false)
      assert.is_not_nil(masked:find('>='))
    end)
  end)

  describe('mask_parentheses / mask_braces / mask_brackets', function()
    it('mask_parentheses masks content', function()
      local input = 'foo(bar, baz)'
      local masked = parse.mask_parentheses(input, false)
      assert.is_not_nil(masked:find('foo'))
      assert.is_nil(masked:find('bar'))
    end)

    it('mask_parentheses keeps enclosing when keep_enclosing=true', function()
      local input = 'foo(bar)'
      local masked = parse.mask_parentheses(input, true)
      assert.is_not_nil(masked:find('%('))
      assert.is_not_nil(masked:find('%)'))
    end)

    it('mask_braces masks content', function()
      local input = 'void foo() { return 1; }'
      local masked = parse.mask_braces(input, false)
      assert.is_nil(masked:find('return'))
    end)

    it('mask_braces keeps enclosing when keep_enclosing=true', function()
      local input = 'void foo() { body }'
      local masked = parse.mask_braces(input, true)
      assert.is_not_nil(masked:find('%{'))
      assert.is_not_nil(masked:find('%}'))
    end)

    it('mask_brackets masks content', function()
      local input = 'arr[10]'
      local masked = parse.mask_brackets(input, false)
      assert.is_not_nil(masked:find('arr'))
      assert.is_nil(masked:find('10'))
    end)

    it('mask_brackets keeps enclosing when keep_enclosing=true', function()
      local input = 'arr[10]'
      local masked = parse.mask_brackets(input, true)
      assert.is_not_nil(masked:find('%['))
      assert.is_not_nil(masked:find('%]'))
    end)
  end)

  describe('strip_default_values', function()
    it('strips simple default values', function()
      eq('int x, int y', parse.strip_default_values('int x = 5, int y = 10'))
    end)
    it('strips string default values', function()
      eq('std::string s', parse.strip_default_values('std::string s = "hello"'))
    end)
    it('handles template defaults', function()
      eq('T val', parse.strip_default_values('T val = T()'))
    end)
    it('returns empty for nil', function()
      eq('', parse.strip_default_values(nil))
    end)
    it('returns empty for blank', function()
      eq('', parse.strip_default_values(''))
    end)
    it('handles single parameter without default', function()
      eq('int x', parse.strip_default_values('int x'))
    end)
    it('handles default with nested braces', function()
      eq('std::function<void()> cb', parse.strip_default_values('std::function<void()> cb = {}'))
    end)
    it('handles default with angle brackets', function()
      eq('T val', parse.strip_default_values('T val = T<int>()'))
    end)
  end)

  describe('matches_primitive_type', function()
    it('matches int', function()
      assert.is_true(parse.matches_primitive_type('int'))
    end)
    it('matches unsigned long', function()
      assert.is_true(parse.matches_primitive_type('unsigned long'))
    end)
    it('matches bool', function()
      assert.is_true(parse.matches_primitive_type('bool'))
    end)
    it('matches auto', function()
      assert.is_true(parse.matches_primitive_type('auto'))
    end)
    it('rejects std::string', function()
      assert.is_false(parse.matches_primitive_type('std::string'))
    end)
    it('rejects template types', function()
      assert.is_false(parse.matches_primitive_type('vector<int>'))
    end)
    it('rejects nil', function()
      assert.is_false(parse.matches_primitive_type(nil))
    end)
    it('rejects empty', function()
      assert.is_false(parse.matches_primitive_type(''))
    end)
    it('matches long long', function()
      assert.is_true(parse.matches_primitive_type('long long'))
    end)
    it('matches unsigned long long', function()
      assert.is_true(parse.matches_primitive_type('unsigned long long'))
    end)
    it('matches long double', function()
      assert.is_true(parse.matches_primitive_type('long double'))
    end)
    it('matches size_t', function()
      assert.is_true(parse.matches_primitive_type('size_t'))
    end)
    it('rejects user-defined types like MyClass', function()
      assert.is_false(parse.matches_primitive_type('MyClass'))
    end)
  end)

  describe('get_parameter_types', function()
    it('returns empty table for nil input', function()
      eq({}, parse.get_parameter_types(nil))
    end)
    it('returns empty table for empty string', function()
      eq({}, parse.get_parameter_types(''))
    end)
    it('extracts type from simple parameter', function()
      eq({ 'int' }, parse.get_parameter_types('int x'))
    end)
    it('extracts types from multiple parameters', function()
      eq({ 'int', 'float' }, parse.get_parameter_types('int x, float y'))
    end)
    it('handles const reference', function()
      eq({ 'const std::string&' }, parse.get_parameter_types('const std::string& name'))
    end)
    it('handles pointer', function()
      eq({ 'int*' }, parse.get_parameter_types('int* ptr'))
    end)
    it('handles pointer with space before asterisk', function()
      eq({ 'int' }, parse.get_parameter_types('int *ptr'))
    end)
    it('handles template type', function()
      eq({ 'std::vector<int>' }, parse.get_parameter_types('std::vector<int> items'))
    end)
    it('handles array parameter', function()
      eq({ 'int' }, parse.get_parameter_types('int arr[10]'))
    end)
    it('strips default values before extracting types', function()
      eq({ 'int', 'float' }, parse.get_parameter_types('int x = 5, float y = 3.14'))
    end)
    it('does not split on commas inside template brackets', function()
      eq({ 'std::map<int, float>', 'int' }, parse.get_parameter_types('std::map<int, float> m, int n'))
    end)
  end)
end)
